set vTableName = 'fator_contribuinte';
set vFileNameOrigin = 'fator_contribuinte.csv';
set vFileNameOutput = 'fator_contribuinte.QVD';

$(vTableName):

LOAD
    codigo_ocorrencia3,
    fator_nome,
    fator_aspecto,
    fator_condicionante,
    fator_area
FROM [$(vPathImport)$(vFileNameOrigin)]
(txt, utf8, embedded labels, delimiter is ';', msq);

store $(vTableName) into [$(vPathExtract) $(vFileNameOutput)](QVD);
Drop Table $(vTableName);