set vTableName = 'fator_contribuinte';
set vFileNameOrigin = 'fator_contribuinte.QVD';
set vFileNameOutput = 'fator_contribuinte.QVD';

$(vTableName):

LOAD
    codigo_ocorrencia3 as %keyFator,
    codigo_ocorrencia3 as Codigo_Fator_Ocorrencia,
    fator_nome,
    fator_aspecto,
    fator_condicionante,
    fator_area
FROM [$(vPathExtract)$(vFileNameOrigin)](QVD);
store $(vTableName) into [$(vPathTransform)$(vFileNameOutput)](QVD);

Drop Table $(vTableName);